
import type { Task, Project } from './types';
import { Priority, RecurrenceFrequency } from './types';

export const initialProjects: Project[] = [
  { id: 'proj-1', name: '新規プロジェクト', color: 'bg-green-500' },
  { id: 'proj-2', name: '経営方針発表会資料', color: 'bg-blue-500' },
  { id: 'proj-3', name: 'ブログ', color: 'bg-yellow-500' },
  { id: 'proj-4', name: '成長支援制度の再設計', color: 'bg-blue-600' },
  { id: 'proj-5', name: '成長支援制度', color: 'bg-pink-500' },
  { id: 'proj-6', name: 'コーポレートページリニューアル', color: 'bg-lime-500' },
];

export const initialTasks: Task[] = [
  {
    id: '1',
    title: 'オクゴニュースレターを読む',
    completed: false,
    priority: Priority.Medium,
    dueDate: new Date(),
    projectId: null,
    tags: ['毎日のタスク'],
    estimatedMinutes: 15,
    completedAt: null,
    createdAt: new Date(),
    recurrence: {
      frequency: RecurrenceFrequency.DAILY,
    }
  },
  {
    id: '2',
    title: 'プルスウルトラJの動画を見る',
    completed: false,
    priority: Priority.Medium,
    dueDate: new Date(),
    projectId: null,
    tags: ['毎日のタスク'],
    estimatedMinutes: 30,
    completedAt: null,
    createdAt: new Date(),
  },
  {
    id: '3',
    title: '神威日報をチェック',
    completed: false,
    priority: Priority.Medium,
    dueDate: new Date(),
    projectId: null,
    tags: ['毎日のタスク'],
    estimatedMinutes: 10,
    completedAt: null,
    createdAt: new Date(),
  },
  {
    id: '4',
    title: '社内メッセージ処理',
    completed: false,
    priority: Priority.Medium,
    dueDate: new Date(),
    projectId: null,
    tags: ['毎日のタスク'],
    estimatedMinutes: 20,
    completedAt: null,
    createdAt: new Date(),
  },
  {
    id: '5',
    title: '売上集計',
    completed: false,
    priority: Priority.High,
    dueDate: new Date(),
    projectId: null,
    tags: ['毎月のタスク'],
    estimatedMinutes: 60,
    completedAt: null,
    createdAt: new Date(),
    recurrence: {
        frequency: RecurrenceFrequency.MONTHLY,
    }
  },
  {
    id: '6',
    title: '部月報',
    completed: false,
    priority: Priority.Medium,
    dueDate: new Date(),
    projectId: null,
    tags: ['毎月のタスク'],
    estimatedMinutes: 45,
    completedAt: null,
    createdAt: new Date(),
  },
  {
    id: '7',
    title: '次のマーケティングキャンペーンを計画する',
    completed: false,
    priority: Priority.High,
    dueDate: new Date(new Date().setDate(new Date().getDate() + 2)),
    projectId: 'proj-3',
    tags: ['マーケティング', '企画'],
    estimatedMinutes: 120,
    completedAt: null,
    createdAt: new Date(),
  },
  {
    id: '8',
    title: '新しいUIモックアップをデザインする',
    completed: true,
    priority: Priority.High,
    dueDate: new Date(new Date().setDate(new Date().getDate() - 1)),
    projectId: 'proj-4',
    tags: ['デザイン', 'UI/UX'],
    estimatedMinutes: 180,
    completedAt: new Date(),
    createdAt: new Date(new Date().setDate(new Date().getDate() - 3)),
  },
  {
    id: '9',
    title: '経費報告書を提出する',
    completed: false,
    priority: Priority.Low,
    dueDate: new Date(new Date().setDate(new Date().getDate() - 2)),
    projectId: 'proj-2',
    tags: ['管理'],
    estimatedMinutes: 15,
    completedAt: null,
    createdAt: new Date(new Date().setDate(new Date().getDate() - 5)),
  },
  {
    id: '10',
    title: 'チーム同期ミーティング',
    completed: false,
    priority: Priority.Medium,
    dueDate: new Date(new Date().setDate(new Date().getDate() + 1)),
    projectId: 'proj-1',
    tags: [],
    estimatedMinutes: 60,
    completedAt: null,
    createdAt: new Date(),
    recurrence: {
        frequency: RecurrenceFrequency.WEEKLY,
        daysOfWeek: [1, 3, 5] // Monday, Wednesday, Friday
    },
    reminder: {
        value: 15,
        unit: 'minutes',
    }
  },
];